src/App.css, src/Components/FormStyles.css
Se agregó el css de los forms que definimos en la daily.
=> [ADD] forms css

package.json, src/App.js, src/Components/Contact/Contact.css, src/Components/Contact/Contact.js, src/Components/Contact/ContactForm.js, src/constants/index.js
Enlace a la tarea [#OT144-36](https://alkemy-labs.atlassian.net/browse/OT144-36)
- Se instaló la librería [Formik](https://formik.org/) para la gestión de este y próximos formularios
- Se creó un componente principal -> Contact
- Se creó el componente ContactForm y se añadieron las respectivas validaciones que requiere la tarea
- Se creó la ruta "/contact" para acceder a este componente
Una preview de lo realizado:
Por ahora, al enviar el formulario solo se imprimen en consola los valores.
=> Task: Contact Form #OT144-36

src/App.js, src/Components/Home/HomePage.js, src/Components/Home/stylesHomePage.css
.Creación de carpeta /Home
.Creación de componente HomePage.js
.Creación de ruta
=> creacion de HomePage

src/App.js, src/Components/ScreenDashboard/ScreenDashboardPage.js, src/Components/ScreenDashboard/stylesScreenDashboardPage.css
.Creación de componente ScreenDashboardPage
.Creación de ruta /backoffice para acceder al componente
=> creacion de componente screenDashboardPage

package.json, src/Components/Users/ImagePreview.jsx, src/Components/Users/UsersForm.js, src/Components/Users/ValidateFunctions.jsx
**Crear o editar usuario existente**
Tareas realizadas: 
- Modifiqué el archivo UserForm.js, integrando la librería de Formik. Agregué el campo de contraseña y el upload para la foto de perfil.  
- Escribí las validaciones de las funciones en un archivo aparte para que el código de UserForm esté mas limpio. Estas funciones lo que hace es activar el error de Formik, cuando el campo es requerido y no hay información dentro o cuando la información colocada es invalida.  
- Coloqué como constante los formatos permitidos para el upload. 
- Creé un componente donde te da un preview de la imagen. 
- Utilicé Axios (get, post y patch) para obtener (en caso de ser existente) el usuario y en el momento del Submit, actualizar o crear los datos del usuario.
Aún por corregir: 
- No están colocados los …
=> Task: Create and edit user

src/Components/Carousel/BtnSlider.js, src/Components/Carousel/Carousel.css, src/Components/Carousel/Carousel.js, src/Components/Carousel/icons/left-arrow.svg, src/Components/Carousel/icons/right-arrow.svg, src/Components/Home/Carousel/Slice.js
Enlace al Ticket [#OT144-53](https://alkemy-labs.atlassian.net/browse/OT144-53)
Tarea realizada:
- Se creo el componente Carousel, recibe por medio de props un array de objetos.
- El componente contiene dos botones para deslizarse de izquierda a derecha por los slides
=> Task/Component-Carousel 

src/App.js, src/Components/News/CKEditorNews.js, src/Components/News/CreateNews.js, src/Components/News/News.css, src/Components/News/NewsForm.js, src/constants/index.js, src/utils/index.js
Enlace a la tarea [OT144-27](https://alkemy-labs.atlassian.net/browse/OT144-27)
- Se creó el component NewsForm con sus validaciones solicitadas en el ticket
- Se estableció de forma reutilizable el comportamiento del formulario, a través de las props  **Mode** y **Novelity**, en caso de que **Mode** sea Create, el formulario llamará el endpoint con el verbo POST, en caso de que no sea ese modo, cargará los inputs del formulario con el objeto **Novelity** y llamará el endpoint con  el verbo PUT con el ID de la novedad.
- Se establecieron las propTypes del component NewsForm.
- Se creó una función en la carpeta **Utils** para extraer en base64 un archivo.
- Se cargan las categorías desde la API para llenar el Select de categorías.
También se valida en los tipos de …
=> Task: Creation News Form #OT144-27

src/Components/Contact/Contact.css
Se cambiaron los valores en pixeles de los breakpoints del componente ContactForm, a los valores acordados por el equipo.
=> Change Old Breakpoints

src/App.js, src/Components/Donations/Donacion.js, src/Components/Donations/Gracias.js, src/Components/Donations/stylesDonacion.css, src/Components/Donations/stylesGracias.css
Creación de componentes Donacion / Gracias
- **Componente Donación:**
1. Se renderiza al ingresar a la ruta /donar 
2. Muestra un texto de forma dinámica (recibido por props "data") 
3. Muestra un botón de mercadopago
- **Componente Gracias**
1.  Se renderiza al ingresar a la ruta /gracias 
2. Muestra un mensaje de agradecimiento
=> task/creacion de componentes donacion/gracias

src/Services/privateApiService.js
Enlace a la tarea [#OT144-69](https://alkemy-labs.atlassian.net/browse/OT144-69)
Se creó un método en el servicio de PrivateApi que obtiene el token almanenado en el localStorage y lo concatena a un string con la palabra Bearer.
=> Task: GetToken Method Security #OT144-69

src/Components/Contact/ServiceAPIContact.js
Ticket asignado: [#OT144-80](https://alkemy-labs.atlassian.net/jira/software/c/projects/OT144/boards/217?modal=detail&selectedIssue=OT144-80)
Tarea realizada: 
- Se creo un servicio HTTP con todos los métodos para utilizar en la sección Contactos
=> create service http contact

src/Services/publicApiService.js
Ticket Asignado: [#OT144-75](https://alkemy-labs.atlassian.net/jira/software/c/projects/OT144/boards/217?modal=detail&selectedIssue=OT144-75)
Tarea realizada:
Se creo un método re utilizable 'POST'
=> Method  public  postRequest

package.json, src/Components/News/Home.js, src/Components/Slides/SlidesList.js, src/actions/actions.js, src/actions/auth.js, src/app/store.js, src/index.js, src/reducers/authReducer.js, src/reducers/rootReducer.js, src/types/index.js, yarn.lock
Enlace a la tarea [OT#144-106](https://alkemy-labs.atlassian.net/browse/OT144-106)
- Se instalaron las dependencias de Redux, React-Redux y Redux-thunk
- Se realizó la configuración base de redux y su store
- Se creó un rootReducer para poder agregar otros reducers al store de manera más fácil.
- Se creó el authReducer
- Se creó el archivo types para usarlos en los actions o reducers para evitar problemas futuros con typos
- Se crearon las actions para el authReducer, con las funciones de login, register y logout (queda pendiente cambiar las peticiones por los métodos del servicio de auth cuando esté listo, también queda por hacer los casos en que falla la request y mostrar la alerta con SweetAlert).
- Se añadió la configuración para poder usar la extensión de Redux …
=> Task: Create authReducer and configuration base Store OT#144-106

src/Components/News/Home.js, src/Components/Slides/SlidesList.js, src/Components/UI/Card/CardListStyles.css
Corregí la información enviada a la card desde news/home.js porque se estaban mandando los datos por separado (título, imagen, descripción, etc) y la card tenía que recibir toda la información en un objeto. Además cambié algunos estilos, porque al recibir correctamente la información, las imágenes se desbordaban de la card.
=> [FIX] send information in news/home.js and card´s css

package.json, src/Components/UI/Alerts/BasicAlert.js, src/Components/UI/Alerts/ConfirmAlert.js, yarn.lock
Enlace a la tarea [#OT144-95](https://alkemy-labs.atlassian.net/browse/OT144-95)
- Se instaló la librería [sweetalert2](https://www.npmjs.com/package/sweetalert2) en lugar de la librería [sweetalert2-react](https://www.npmjs.com/package/sweetalert2-react), ya que esta última desde hace tres años no recibe soporte.
- Se creó el component BasicAlert que recibe las props de type (success, error, warning, info o question), title, text y el timer que es el tiempo que tarda en cerrarse la alerta, aquí un ejemplo:
- Se creó el component ConfirmAlert que recibe las props de type (success, error, warning, info o question), title, text, confirmButtonText (texto dentro del botón de confirmar) y cancelButtonText (texto dentro del botón de cancelar), aquí un ejemplo:
Tengo una …
=> Task: Setup Alerts #OT144-95

.env.example, src/Components/Members/membersService.js
Ticket asignado: [#OT144-87](https://alkemy-labs.atlassian.net/jira/software/c/projects/OT144/boards/217?modal=detail&selectedIssue=OT144-87)
Tareas realizadas: 
- Almacenar el endpoint para miembros en una variable de entorno.
- Se excluyo el archivo .env del commit.
- Se commiteo el archivo .env.example con el placeholder de .env
=> Task/Env Variable Endpoints Members

README.md, src/Components/UI/LinearProgress/LinearProgress.css, src/Components/UI/LinearProgress/index.js
[OT144-94](https://alkemy-labs.atlassian.net/browse/OT144-94)
- Se creo el componente Linear Progress con su respectivo archivo css. Para las animaciones se utilizo css nativo.
**Incluidos en el archivo Read.Me**
=> Setup Progress

src/Components/Home/HomePage.js, yarn.lock
Enlace a la tarea [OT144#101](https://alkemy-labs.atlassian.net/browse/OT144-101)
- Se realizó la petición de slides y se dejó indicada la petición para traerse las novedades.
- Se mostrará la alerta de error en caso de que falle la petición.
=> Task: Show errors in Home OT144#101

src/Components/Slides/SlidesList.js, src/actions/slider.js, src/reducers/rootReducer.js, src/reducers/sliderReducer.js, src/types/sliderTypes.js
Tarea asignada:[#OT-144-110](https://alkemy-labs.atlassian.net/browse/OT144-110)
Tareas realizadas :
-Se creo reducer para gestionar el estado de los Sliders.
-Peticiones de la API se almaceno en el reducer.
=> Task/reducer slider 

src/Components/Home/BackOffice/Novedades.js, src/Components/UI/Errors/UserIsAdmin.js
Se corrigió un fix en userIsAdmin porque siempre daba false, debido a que comparaba lo que retornaba del localStorage que es un string, con el numero 1. Por eso siempre daba false.
=> [FIX]error in userIsAdmin

src/App.js
Utilicé la función creada por @marsl27, con la diferencia de que en la operación ternaria, redirige al usuario a la página de Login.
Queda por cambiar los Navigate por history luego de que se migre el router a v5.
=> Task/Private Routes protected

src/Components/Home/BackOffice/HeaderComponent.js, src/Components/Home/BackOffice/stylesHeaderComponent.css, src/actions/auth.js
Enlace a la tarea [OT144#140](https://alkemy-labs.atlassian.net/browse/OT144-140)
- Se muestra condicionalmente el botón si el usuario está autentificado.
- Se agregó a la action de startLogout las acciones de borrar los datos de Email y Role del localstorage
=> Task: Create Logout Logic OT144#140

src/Components/Users/UsersList/UsersList.js, src/Components/Users/UsersList/UsersTable.js, src/Services/userService.js
**Buscador de Usarios por Rol**
Se añadió un field select al buscador de usuarios, que permite filtrar por usuarios regulares o administradores haciendo una petición (que también fue agregada) desde userService. También se colocó una colmuna nueva para describir el rol de cada usuario. 
Lo curioso de esta petición es que cuando se filtran los administradores, no figura ninguno, ya que realiza una petición limitada de usuarios.
=> Task/Search users by Role

src/Components/Home/BackOffice/ActivitiesTable.js, src/actions/Activities.js
**Arreglo componente "ActivitiesTable"**
Se unificaron las correcciones de @marsl27 y las que había realizado anteriormente para implementar el buscador de actividades por título.
=> Arreglo componente activities table

src/Components/News/CreateNews.js, src/Components/News/News.css, src/Components/News/NewsForm.js
**Componente NewsForm**
Se arreglo la implementación de los componentes "BasicAlert' y "ErrorAlert"
=> Arreglo componente NewsForm

public/index.html
Se agrego el icono y el name al titulo de head en el archivo html
=> add icon and name ONG

src/Campaigns/Toys/Footer.css
No me convencía como me había quedado ese box-shadow  en los botones de las redes sociales en el componente Footer.js y opte por sacarlos :stuck_out_tongue:
=> delete box-shadow Footer.css

src/Components/Home/stylesHomePage.css, src/Components/Layout/LayoutPublic.css
Se eliminaron los background- colors de el componente HomePage.css y se cambio el color del background en el  componente LayoutPublic.css
Así quedó!
=> Background layout

src/Components/Activities/ActivitiesForm/ActivitiesForm.css, src/Components/Activities/ActivitiesForm/ActivitiesForm.js, src/Components/Home/BackOffice/ActivitiesTable.js, src/Components/Home/BackOffice/RedirectActivities.js, src/Components/Home/BackOffice/ui/sidebarBackOffice/SidebarBackOffice.js, src/Components/Home/BackOffice/ui/sidebarBackOffice/sidebarBackOffice.css, src/assets/activities.svg
La interfaz entera de actividades del lado del backoffice sirve, para editar, eliminar y crear una actividad, todas con sus respectivas alertas.
Adicionalmente se eliminó el header duplicado que había
=> Fix: Activities errors

src/Components/About/AboutUs.js, src/Components/About/stylesAboutUs.css, src/Components/Contact/Contact.css, src/Components/Contact/Contact.js, src/Components/Donations/Donacion.js, src/Components/Donations/stylesDonacion.css, src/Components/Layout/LayoutPublic.css, src/Components/News/Detail/DetailContent.js, src/Components/News/Detail/stylesDetailNew.css, src/Components/UI/PresentationPage/stylesPresentationPage.css
**En la parte pública:**
Se hizo estándar el width y el justificado de los textos
Se modificó el responsive del formulario en el componente "Contacto"
Se dió margen al btn de donación en el componente "Donar"
Se agrego espacios entre los componentes
=> Se hizo estandar el width y el justificado de los textos

src/Components/Contact/Contact.css, src/Components/Contact/Contact.js, src/Components/Contact/ContactForm.js
Responsive el form de "Contacto"
=> responsive form de contacto

src/Components/About/AboutPrincipal.js, src/Components/FormStyles.css, src/Components/UI/ReactSocialPlugins/ReactSocialPlugins.js, src/Components/UI/ReactSocialPlugins/stylesCardLinkedin.css, src/Components/UI/ReactSocialPlugins/stylesReactSocialPlugins.css
Se hizo responsive el formulario de login
Se agrego componente ReactSocialPlugins a "Nosotros"
=> se agrego componente reactSocialPlugins a nosotros

src/Components/Testimonials/TestimonialsTable.jsx, src/Services/TestimonialsApiService.js
Se agregó la lógica del botón de eliminar en el backoffice de testimonios y se borraron testimonios.
=> [DELETE] testimonials

src/Components/Carousel/Carousel.css, src/Components/Home/HomePage.js, src/Components/Home/stylesHomePage.css
Se modificaron estilos de la "Home" public
=> se modifico estilos de la home

src/Components/Carousel/Carousel.js, src/Components/News/Detail/DetailContent.js, src/Components/News/Detail/stylesDetailNew.css, src/Components/Testimonials/DetailTestimonials.jsx, src/Components/Testimonials/Testimonials.css, src/Components/UI/Card/Card.jsx, src/Components/UI/Card/CardListStyles.css
- Se renderiza correctamente el HTML que proviene de la API, para los componentes de cards y detail de las secciones de: News, Testimonials, Activities, Members y Slides
Antes: 
Después:
=> Fix: Rendering HTML
